import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import Chart from 'https://cdn.jsdelivr.net/npm/chart.js@4.4.4/auto/+esm';
import { jsPDF } from 'https://cdn.jsdelivr.net/npm/jspdf@2.5.2/+esm';

const SUPABASE_URL='https://sjuizodatqyfocjbbuqz.supabase.co';
const SUPABASE_KEY='sb_publishable_gDOi7KQI3cDnojCvqs8eIQ_Sm-VkjnS';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const DEFAULT_MODEL={version:'v0.1-priors',heat_weight:.4,cold_weight:.15,drought_weight:.25,excess_weight:.2,critical_days_before:15,critical_days_after:15,tmax_heat_c:35,tmin_cold_c:4};
const TEMP_MEAN={9:16.5,10:19.5,11:22,12:24.2,1:25,2:24,3:21.5,4:17.5};
const FALLBACK_PRIORS={'09-2':{heat:5,cold:8,drought:30,excess:15},'10-1':{heat:8,cold:4,drought:25,excess:20},'10-2':{heat:12,cold:2,drought:20,excess:22},'11-1':{heat:18,cold:1,drought:18,excess:25},'11-2':{heat:25,cold:1,drought:15,excess:28},'12-1':{heat:35,cold:.5,drought:15,excess:30},'12-2':{heat:45,cold:.5,drought:12,excess:32},'01-1':{heat:55,cold:.5,drought:12,excess:35},'01-2':{heat:60,cold:.5,drought:10,excess:35},'02-1':{heat:50,cold:2,drought:10,excess:30},'02-2':{heat:40,cold:3,drought:12,excess:25},'03-1':{heat:20,cold:8,drought:15,excess:20},'03-2':{heat:10,cold:15,drought:18,excess:18}};
const ENSO_FACTORS={Nino:{heat:1,cold:1,drought:1,excess:1},Neutral:{heat:1.04,cold:1,drought:1.15,excess:.88},Nina:{heat:1.10,cold:1,drought:1.35,excess:.72}};
let state={user:null,hybrids:[],farms:[],fields:[],priors:{},observed:[],model:{...DEFAULT_MODEL},history:[],tab:'dashboard',last:null,charts:[]};

const $=s=>document.querySelector(s); const app=()=>$('#app');
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function dparse(v){const [y,m,d]=v.split('-').map(Number);return new Date(Date.UTC(y,m-1,d))}
function iso(d){return d.toISOString().slice(0,10)} function addDays(d,n){const x=new Date(d);x.setUTCDate(x.getUTCDate()+n);return x}
function fmt(d){return new Intl.DateTimeFormat('es-AR').format(d)}
function fortnightKey(d){const m=String(d.getUTCMonth()+1).padStart(2,'0');return `${m}-${d.getUTCDate()<=15?'1':'2'}`}
function clamp(v){return Math.max(0,Math.min(100,v))}
function riskClass(s){if(s<=20)return['Muy bajo','low'];if(s<=35)return['Bajo','low'];if(s<=50)return['Moderado','medium'];if(s<=70)return['Alto','high'];return['Muy alto','veryhigh']}
function clearCharts(){state.charts.forEach(c=>{try{c.destroy()}catch{}});state.charts=[]}

async function bootstrap(){const {data}=await supabase.auth.getSession();state.user=data.session?.user||null;if(!state.user)return loginView();await loadReference();await loadUserData();render();}
async function loadReference(){
  const [h,m,p,o]=await Promise.all([
    supabase.from('hybrids').select('*').eq('active',true).order('name'),
    supabase.from('model_config').select('*').order('version',{ascending:false}).limit(1),
    supabase.from('risk_priors').select('*').order('id'),
    supabase.from('observed_risk_stats').select('*')
  ]);
  if(h.data?.length)state.hybrids=h.data;
  if(m.data?.length)state.model={...DEFAULT_MODEL,...m.data[0]};
  if(p.data?.length){state.priors={};p.data.forEach(x=>state.priors[x.fortnight]={heat:Number(x.p_heat)*100,cold:Number(x.p_cold)*100,drought:Number(x.p_drought)*100,excess:Number(x.p_excess)*100});}else state.priors={...FALLBACK_PRIORS};
  state.observed=o.data||[];
}
async function loadUserData(){
  const [fa,fi,hi]=await Promise.all([
    supabase.from('farms').select('*').order('name'),
    supabase.from('fields').select('*, farms(name)').order('name'),
    supabase.from('simulations').select('*, hybrids(name,biotechnology)').order('created_at',{ascending:false}).limit(100)
  ]);
  state.farms=fa.data||[];state.fields=fi.data||[];state.history=hi.data||[];
}

function loginView(){app().innerHTML=`<div class="login"><div class="card"><div class="brand"><h1>AgroClima Maíz</h1><p>Riesgo agroclimático y decisiones de siembra.</p></div><form id="loginForm"><label class="label">Email</label><input id="email" type="email" required><label class="label">Contraseña</label><input id="password" type="password" minlength="6" required><div class="actions"><button class="primary">Ingresar</button><button id="signup" class="secondary" type="button">Crear usuario</button></div></form><div class="note">La app guarda tus campos, lotes y simulaciones en Supabase. Cada usuario accede sólo a sus propios datos.</div></div></div>`;
  $('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const {data,error}=await supabase.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error)return alert(error.message);state.user=data.user;await bootstrap();});
  $('#signup').addEventListener('click',async()=>{const {error}=await supabase.auth.signUp({email:$('#email').value,password:$('#password').value});alert(error?error.message:'Usuario creado. Si la confirmación de email está activa, revisá tu correo.');});
}

function shell(content){return `<div class="app"><div class="header"><div class="brand"><h1>AgroClima Maíz</h1><p>Centro-norte de Córdoba · herramienta de decisión agronómica</p></div><div class="userbar"><span class="muted">${esc(state.user?.email||'')}</span><button id="logout" class="ghost">Salir</button></div></div><div class="tabs">${[['dashboard','Resumen'],['simulate','Nueva simulación'],['history','Historial'],['hybrids','Híbridos'],['fields','Campos y lotes']].map(([k,n])=>`<button class="tab ${state.tab===k?'active':''}" data-tab="${k}">${n}</button>`).join('')}</div>${content}</div>`}
function render(){clearCharts();let content=state.tab==='simulate'?simulateView():state.tab==='history'?historyView():state.tab==='hybrids'?hybridsView():state.tab==='fields'?fieldsView():dashboardView();app().innerHTML=shell(content);bindCommon();bindTab();}
function bindCommon(){$('#logout').addEventListener('click',async()=>{await supabase.auth.signOut();state.user=null;loginView();});}
function bindTab(){document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{state.tab=b.dataset.tab;render();}));if(state.tab==='simulate')bindSimulation();if(state.tab==='fields')bindFields();if(state.tab==='hybrids')bindHybridCards();if(state.tab==='history')bindHistory();}

function dashboardView(){
  const last=state.history[0];const obs=state.observed.length>0;const farms=state.farms.length;const fields=state.fields.length;
  return `<div class="grid"><div class="card span3"><div class="muted">Campos</div><div class="kpi">${farms}</div></div><div class="card span3"><div class="muted">Lotes</div><div class="kpi">${fields}</div></div><div class="card span3"><div class="muted">Simulaciones</div><div class="kpi">${state.history.length}</div></div><div class="card span3"><div class="muted">Motor climático</div><div class="kpi">${obs?'Observado':'Priors'} <small>${obs?'calibrado':'provisional'}</small></div></div>
  <div class="card span7"><div class="section-title"><h2>Decisión rápida</h2><button class="primary" data-tab="simulate">Nueva simulación</button></div><p>AgroClima combina fecha de siembra, fenología del híbrido, período crítico y riesgo climático para comparar alternativas.</p><div class="note ${obs?'':'warning'}"><b>${obs?'Probabilidades observadas disponibles':'Modelo provisional'}</b><br>${obs?'La tabla observed_risk_stats ya contiene datos y el motor prioriza esas frecuencias.':'Todavía se usan priors heurísticos. La app lo informa en cada resultado y cambiará automáticamente cuando carguemos probabilidades observadas.'}</div></div>
  <div class="card span5"><h2>Última consulta</h2>${last?`<div class="kpi">${Math.round(last.risk_score||0)}/100 <small>${esc(last.risk_class||'')}</small></div><p><b>${esc(last.field_name||'Sin lote')}</b> · ${esc(last.hybrids?.name||'Híbrido')} ${esc(last.hybrids?.biotechnology||'')}</p><p class="muted">Siembra ${esc(last.sowing_date||'')} · R1 ${esc(last.flowering_date||'')}</p>`:'<div class="empty">Todavía no hay consultas guardadas.</div>'}</div></div>`;
}

function hybridOption(h){return `<option value="${h.id}">${esc(h.name)}${h.biotechnology?` — ${esc(h.biotechnology)}`:''}</option>`}
function fieldOptions(){return `<option value="">Sin lote guardado</option>${state.fields.map(f=>`<option value="${f.id}">${esc(f.farms?.name||'Campo')} — ${esc(f.name)}</option>`).join('')}`}
function simulateView(){return `<div class="grid"><div class="card span5"><h2>Nueva simulación</h2><form id="simForm"><label class="label">Lote</label><select id="fieldId">${fieldOptions()}</select><label class="label">Nombre libre (opcional)</label><input id="fieldName" placeholder="Ej. Costa Sacate Lote 1"><label class="label">Híbrido</label><select id="hybridId" required>${state.hybrids.map(hybridOption).join('')}</select><div id="hybridSummary"></div><div class="form-row"><div><label class="label">Fecha de siembra</label><input id="sow" type="date" value="2026-10-05" required></div><div><label class="label">Escenario ENSO</label><select id="enso"><option value="Nino">Niño</option><option value="Neutral">Neutral</option><option value="Nina">Niña</option></select></div></div><div class="form-row"><div><label class="label">Agua útil inicial (mm)</label><input id="water" type="number" min="0" max="350" placeholder="Ej. 140"></div><div><label class="label">Densidad objetivo (pl/ha)</label><input id="density" type="number" min="20000" max="120000" step="1000" placeholder="Ej. 70000"></div></div><label class="label">Ambiente</label><select id="environment"><option value="">Sin especificar</option><option>Alto potencial</option><option>Medio</option><option>Restrictivo</option></select><div class="actions"><button class="primary">Analizar siembra</button></div></form></div><div class="card span7" id="result"><h2>Resultado</h2><p class="muted">Completá una simulación para ver fecha estimada de R1, período crítico, riesgos, alternativas y recomendación.</p></div></div>`}
function selectedHybrid(){return state.hybrids.find(h=>String(h.id)===$('#hybridId').value)}
function bindSimulation(){const select=$('#hybridId');const update=()=>{$('#hybridSummary').innerHTML=hybridMini(selectedHybrid())};select.addEventListener('change',update);update();$('#simForm').addEventListener('submit',runSimulation);}
function hybridMini(h){if(!h)return'';const pub=h.published_gdu_to_flowering?`${h.published_gdu_to_flowering} GDU${h.published_gdu_base_c?` base ${h.published_gdu_base_c}°C`:''}`:(h.flowering_days_reference?`${h.flowering_days_reference} días ref.`:'Sin dato comparable');return `<div class="note"><b>${esc(h.company||'')} · ${esc(h.technology_verified||h.biotechnology||'')}</b><br>MR ${h.relative_maturity??'s/d'} · ${esc(h.cycle||'s/d')} · Fenología publicada: ${pub}.<br><span class="muted">Para el cálculo se usa ${h.model_gdu_fallback||h.gdu_to_flowering||790} GDU base ${h.model_base_temp_fallback_c||h.base_temp_c||10}°C salvo que exista un GDU publicado comparable en base 10.</span></div>`}
function modelPhenology(h){if(h?.published_gdu_to_flowering && Number(h.published_gdu_base_c)===10)return{gdu:Number(h.published_gdu_to_flowering),base:10,source:'GDU publicado comparable'};return{gdu:Number(h?.model_gdu_fallback||h?.gdu_to_flowering||790),base:Number(h?.model_base_temp_fallback_c||h?.base_temp_c||10),source:'fallback operativo'};}
function estimateFlowering(sow,gdu,base){let d=new Date(sow),acc=0,guard=0;while(acc<gdu&&guard<240){const t=TEMP_MEAN[d.getUTCMonth()+1]??18;acc+=Math.max(0,t-base);d=addDays(d,1);guard++;}return{date:d,days:guard,gdu:Math.round(acc)}}
function observedValue(phase,key,metric){const names={heat:['heat','tmax','hot'],cold:['cold','tmin'],drought:['drought','dry'],excess:['excess','wet','rain']};const row=state.observed.find(r=>String(r.phase).toLowerCase()===phase.toLowerCase()&&r.fortnight===key&&names[metric].some(n=>String(r.metric).toLowerCase().includes(n)));if(!row)return null;const p=Number(row.probability);return p<=1?p*100:p;}
function riskAtDate(d,phase,metric){const key=fortnightKey(d);const observed=observedValue(phase,key,metric);if(observed!=null)return clamp(observed);const base=(state.priors[key]||FALLBACK_PRIORS[key]||{heat:20,cold:3,drought:20,excess:25})[metric];return clamp(base*(ENSO_FACTORS[phase]?.[metric]||1));}
function avgWindow(start,end,phase,metric){let d=new Date(start),vals=[];while(d<=end){vals.push(riskAtDate(d,phase,metric));d=addDays(d,1)}return vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):0}
function scoreRisk(r){const m=state.model;return Math.round(r.heat*Number(m.heat_weight??.4)+r.cold*Number(m.cold_weight??.15)+r.drought*Number(m.drought_weight??.25)+r.excess*Number(m.excess_weight??.2))}
function densityAdvice(h,density,environment){if(!density)return'';if(h?.density_min_pl_ha&&density<h.density_min_pl_ha)return`La densidad ${density.toLocaleString('es-AR')} pl/ha está por debajo del rango técnico publicado (${h.density_min_pl_ha.toLocaleString('es-AR')}–${h.density_max_pl_ha?.toLocaleString('es-AR')||'?'}).`;if(h?.density_max_pl_ha&&density>h.density_max_pl_ha)return`La densidad ${density.toLocaleString('es-AR')} pl/ha supera el máximo publicado (${h.density_max_pl_ha.toLocaleString('es-AR')} pl/ha).`;if(environment==='Restrictivo'&&density>75000)return'En ambiente restrictivo, revisar una densidad alta frente a la oferta hídrica esperada.';return''}
function makeRecommendation(r,score,best,h,density,environment,source){const [klass]=riskClass(score);const dominant=Object.entries(r).sort((a,b)=>b[1]-a[1])[0];const names={heat:'calor extremo',cold:'frío extremo',drought:'déficit hídrico',excess:'exceso hídrico'};let txt=`Riesgo ${klass.toLowerCase()}. El factor dominante es ${names[dominant[0]]} (${dominant[1]}%). `;if(best.score<score-2)txt+=`Mover la siembra hacia ${fmt(best.date)} reduce el score estimado a ${best.score}/100. `;else txt+='La fecha elegida está dentro de las mejores alternativas del rango ±20 días. ';const da=densityAdvice(h,density,environment);if(da)txt+=da+' ';if(h?.positioning)txt+=`Posicionamiento del híbrido: ${h.positioning} `;txt+=source==='observed'?'El riesgo usa frecuencias observadas disponibles.':'El riesgo climático todavía usa priors/ajustes provisionales; no debe interpretarse como probabilidad histórica definitiva.';return txt}
async function runSimulation(e){e.preventDefault();const h=selectedHybrid();const phen=modelPhenology(h);const sow=dparse($('#sow').value);const phase=$('#enso').value;const fl=estimateFlowering(sow,phen.gdu,phen.base);const before=Number(state.model.critical_days_before??15),after=Number(state.model.critical_days_after??15);const cs=addDays(fl.date,-before),ce=addDays(fl.date,after);const r={heat:avgWindow(cs,ce,phase,'heat'),cold:avgWindow(cs,ce,phase,'cold'),drought:avgWindow(cs,ce,phase,'drought'),excess:avgWindow(cs,ce,phase,'excess')};const score=scoreRisk(r);const alts=[];for(let delta=-20;delta<=20;delta+=5){const sd=addDays(sow,delta),ff=estimateFlowering(sd,phen.gdu,phen.base),a=addDays(ff.date,-before),b=addDays(ff.date,after);const rr={heat:avgWindow(a,b,phase,'heat'),cold:avgWindow(a,b,phase,'cold'),drought:avgWindow(a,b,phase,'drought'),excess:avgWindow(a,b,phase,'excess')};alts.push({date:sd,score:scoreRisk(rr)})}const best=alts.reduce((a,b)=>a.score<=b.score?a:b);const field=state.fields.find(f=>String(f.id)===$('#fieldId').value);const free=$('#fieldName').value.trim();const fieldName=free||(field?`${field.farms?.name||''} ${field.name}`.trim():'Sin especificar');const density=Number($('#density').value)||null;const water=Number($('#water').value)||null;const environment=$('#environment').value||null;const source=state.observed.length?'observed':'heuristic';const recommendation=makeRecommendation(r,score,best,h,density,environment,source);state.last={h,phen,sow,fl,cs,ce,r,score,alts,best,phase,field,fieldName,density,water,environment,recommendation,source};renderResult();await saveSimulation();await loadUserData();}
function riskRows(r){const labels={heat:'Calor extremo',cold:'Frío extremo',drought:'Déficit hídrico',excess:'Exceso hídrico'};return Object.entries(r).map(([k,v])=>`<div class="risk-row"><span>${labels[k]}</span><div class="bar"><span style="width:${v}%"></span></div><b>${v}%</b></div>`).join('')}
function renderResult(){const x=state.last;const [label,klass]=riskClass(x.score);$('#result').innerHTML=`<div class="section-title"><h2>Resultado</h2><span class="badge ${klass}">${label}</span></div><div class="kpi">${x.score}/100 <small>score combinado</small></div><p><b>R1 estimada:</b> ${fmt(x.fl.date)} · <b>Período crítico:</b> ${fmt(x.cs)}–${fmt(x.ce)}</p><p class="muted">Fenología usada: ${x.phen.gdu} GDU base ${x.phen.base}°C (${x.phen.source}).</p>${riskRows(x.r)}<div class="note"><b>Recomendación</b><br>${esc(x.recommendation)}</div><div class="actions"><button id="pdfBtn" class="primary">Descargar PDF</button><button id="hybridBtn" class="secondary">Ver ficha del híbrido</button></div><canvas id="compareChart"></canvas>`;drawCompare();$('#pdfBtn').addEventListener('click',downloadPdf);$('#hybridBtn').addEventListener('click',()=>{state.tab='hybrids';render();setTimeout(()=>{const el=document.querySelector(`[data-hybrid-card="${x.h.id}"]`);el?.scrollIntoView({behavior:'smooth',block:'start'})},100)});}
function drawCompare(){const x=state.last;const c=new Chart($('#compareChart'),{type:'line',data:{labels:x.alts.map(a=>fmt(a.date)),datasets:[{label:'Score',data:x.alts.map(a=>a.score),tension:.25}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,max:100,title:{display:true,text:'Riesgo 0–100'}},x:{title:{display:true,text:'Fecha de siembra'}}}}});state.charts.push(c)}
async function saveSimulation(){const x=state.last;const payload={user_id:state.user.id,field_id:x.field?.id||null,field_name:x.fieldName,hybrid_id:x.h.id,sowing_date:iso(x.sow),flowering_date:iso(x.fl.date),critical_start:iso(x.cs),critical_end:iso(x.ce),enso_phase:x.phase,risk_heat:x.r.heat,risk_cold:x.r.cold,risk_drought:x.r.drought,risk_excess:x.r.excess,risk_score:x.score,risk_class:riskClass(x.score)[0],recommendation:x.recommendation,model_version:state.model.version||'v0.1-priors',water_initial_mm:x.water,target_density_pl_ha:x.density,environment:x.environment,risk_source:x.source,hybrid_snapshot:`${x.h.name} — ${x.h.biotechnology||''}`};const {error}=await supabase.from('simulations').insert(payload);if(error)alert('La simulación se calculó, pero no pudo guardarse: '+error.message)}
function downloadPdf(){const x=state.last;if(!x)return;const d=new jsPDF();d.setFontSize(19);d.text('AgroClima Maíz',14,18);d.setFontSize(10);d.text('Informe de riesgo agroclimático',14,25);let y=38;const rows=[['Campo/lote',x.fieldName],['Híbrido',`${x.h.name} ${x.h.biotechnology||''}`],['Empresa',x.h.company||'s/d'],['Siembra',fmt(x.sow)],['R1 estimada',fmt(x.fl.date)],['Período crítico',`${fmt(x.cs)} a ${fmt(x.ce)}`],['ENSO',x.phase],['Fenología usada',`${x.phen.gdu} GDU base ${x.phen.base} °C`],['Score',`${x.score}/100 - ${riskClass(x.score)[0]}`],['Calor',`${x.r.heat}%`],['Déficit',`${x.r.drought}%`],['Exceso',`${x.r.excess}%`],['Frío',`${x.r.cold}%`]];rows.forEach(([a,b])=>{d.setFont(undefined,'bold');d.text(a+':',14,y);d.setFont(undefined,'normal');d.text(String(b),62,y);y+=7});y+=5;d.setFont(undefined,'bold');d.text('Recomendación',14,y);y+=7;d.setFont(undefined,'normal');d.text(d.splitTextToSize(x.recommendation,180),14,y);y+=38;if(x.h.sanitary_profile){d.setFont(undefined,'bold');d.text('Perfil sanitario',14,y);y+=7;d.setFont(undefined,'normal');d.text(d.splitTextToSize(x.h.sanitary_profile,180),14,y)}d.setFontSize(8);d.text(x.source==='observed'?'Riesgo: frecuencias observadas disponibles.':'Riesgo: priors/ajustes provisionales hasta completar calibración histórica.',14,286);d.save(`AgroClima_${x.h.name.replace(/\s+/g,'_')}_${iso(x.sow)}.pdf`)}

function historyView(){return `<div class="card"><div class="section-title"><h2>Historial de simulaciones</h2><span class="muted">${state.history.length} registros</span></div>${state.history.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Fecha</th><th>Campo/Lote</th><th>Híbrido</th><th>Siembra</th><th>R1</th><th>ENSO</th><th>Score</th><th></th></tr></thead><tbody>${state.history.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString('es-AR')}</td><td>${esc(x.field_name||'')}</td><td>${esc(x.hybrids?.name||x.hybrid_snapshot||'')} ${esc(x.hybrids?.biotechnology||'')}</td><td>${esc(x.sowing_date||'')}</td><td>${esc(x.flowering_date||'')}</td><td>${esc(x.enso_phase||'')}</td><td><span class="badge ${riskClass(Number(x.risk_score||0))[1]}">${Math.round(x.risk_score||0)}/100</span></td><td><button class="danger" data-delete-sim="${x.id}">Eliminar</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Todavía no hay simulaciones.</div>'}</div>`}
function bindHistory(){document.querySelectorAll('[data-delete-sim]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('¿Eliminar esta simulación?'))return;const {error}=await supabase.from('simulations').delete().eq('id',b.dataset.deleteSim);if(error)return alert(error.message);await loadUserData();render();}));}

function hybridsView(){return `<div class="grid"><div class="card span12"><div class="section-title"><h2>Biblioteca de híbridos</h2><span class="muted">${state.hybrids.length} versiones activas</span></div><p class="muted">La ficha distingue datos publicados, datos validados por usuario y valores fallback del modelo.</p></div>${state.hybrids.map(h=>`<div class="card span6" data-hybrid-card="${h.id}"><div class="section-title"><h3>${esc(h.name)} — ${esc(h.biotechnology||'')}</h3><span class="badge ${h.data_status==='validado_publico'?'low':'medium'}">${esc(h.data_status||'')}</span></div><p class="muted">${esc(h.company||'')} · MR ${h.relative_maturity??'s/d'} · ${esc(h.cycle||'s/d')}</p><div class="profile-grid"><div class="mini">Tecnología<b>${esc(h.technology_verified||h.technology||'s/d')}</b></div><div class="mini">GDU publicado<b>${h.published_gdu_to_flowering??'s/d'}${h.published_gdu_base_c?` · base ${h.published_gdu_base_c}°C`:''}</b></div><div class="mini">Días floración ref.<b>${h.flowering_days_reference??'s/d'}</b></div><div class="mini">Estabilidad<b>${h.stability_score?`${h.stability_score}/5`:'s/d'}</b></div><div class="mini">Densidad mínima<b>${h.density_min_pl_ha?Number(h.density_min_pl_ha).toLocaleString('es-AR'):'s/d'}</b></div><div class="mini">Densidad máxima<b>${h.density_max_pl_ha?Number(h.density_max_pl_ha).toLocaleString('es-AR'):'s/d'}</b></div></div><p><b>Sanidad:</b> ${esc(h.sanitary_profile||'Sin dato público verificado.')}</p><p><b>Posicionamiento:</b> ${esc(h.positioning||'Sin dato público verificado.')}</p><p class="muted">${esc(h.observations||'')}</p>${h.source_url?`<a class="source-link" href="${esc(h.source_url)}" target="_blank" rel="noopener">Fuente técnica</a>`:''}</div>`).join('')}</div>`}
function bindHybridCards(){}

function fieldsView(){return `<div class="grid"><div class="card span5"><h2>Nuevo campo</h2><form id="farmForm"><label class="label">Nombre</label><input id="farmName" required placeholder="Ej. Costa Sacate"><label class="label">Localidad</label><input id="farmLocality" placeholder="Ej. Costa Sacate"><div class="form-row"><div><label class="label">Latitud</label><input id="farmLat" type="number" step="any"></div><div><label class="label">Longitud</label><input id="farmLon" type="number" step="any"></div></div><button class="primary" style="margin-top:14px">Guardar campo</button></form><hr style="border:0;border-top:1px solid var(--border);margin:20px 0"><h2>Nuevo lote</h2><form id="fieldForm"><label class="label">Campo</label><select id="fieldFarm" required>${state.farms.map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join('')}</select><label class="label">Nombre del lote</label><input id="newFieldName" required><div class="form-row"><div><label class="label">Área (ha)</label><input id="fieldArea" type="number" step="0.01"></div><div><label class="label">Profundidad de suelo</label><select id="soilDepth"><option value="">Sin dato</option><option>Profundo</option><option>Medio</option><option>Somero</option></select></div></div><label class="label">Ambiente</label><select id="fieldEnv"><option value="">Sin dato</option><option>Alto potencial</option><option>Medio</option><option>Restrictivo</option></select><button class="primary" style="margin-top:14px" ${state.farms.length?'':'disabled'}>Guardar lote</button></form></div><div class="card span7"><h2>Mis campos y lotes</h2>${state.farms.length?state.farms.map(f=>`<div class="history-item"><div class="history-top"><strong>${esc(f.name)}</strong><button class="danger" data-delete-farm="${f.id}">Eliminar</button></div><div class="muted">${esc(f.locality||'')} ${f.latitude!=null?`· ${f.latitude}, ${f.longitude}`:''}</div>${state.fields.filter(x=>x.farm_id===f.id).map(x=>`<div style="margin:8px 0 0 12px">↳ <b>${esc(x.name)}</b> ${x.area_ha?`· ${x.area_ha} ha`:''} ${x.environment?`· ${esc(x.environment)}`:''} <button class="danger" data-delete-field="${x.id}" style="padding:5px 8px">Eliminar</button></div>`).join('')}</div>`).join(''):'<div class="empty">Todavía no cargaste campos.</div>'}</div></div>`}
function bindFields(){
  $('#farmForm').addEventListener('submit',async e=>{e.preventDefault();const payload={user_id:state.user.id,name:$('#farmName').value.trim(),locality:$('#farmLocality').value.trim()||null,latitude:$('#farmLat').value?Number($('#farmLat').value):null,longitude:$('#farmLon').value?Number($('#farmLon').value):null};const {error}=await supabase.from('farms').insert(payload);if(error)return alert(error.message);await loadUserData();render();});
  $('#fieldForm').addEventListener('submit',async e=>{e.preventDefault();const payload={farm_id:$('#fieldFarm').value,name:$('#newFieldName').value.trim(),area_ha:$('#fieldArea').value?Number($('#fieldArea').value):null,soil_depth:$('#soilDepth').value||null,environment:$('#fieldEnv').value||null};const {error}=await supabase.from('fields').insert(payload);if(error)return alert(error.message);await loadUserData();render();});
  document.querySelectorAll('[data-delete-field]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('¿Eliminar este lote?'))return;const {error}=await supabase.from('fields').delete().eq('id',b.dataset.deleteField);if(error)return alert(error.message);await loadUserData();render();}));
  document.querySelectorAll('[data-delete-farm]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Eliminar el campo también elimina sus lotes. ¿Continuar?'))return;const {error}=await supabase.from('farms').delete().eq('id',b.dataset.deleteFarm);if(error)return alert(error.message);await loadUserData();render();}));
}

bootstrap();
